### 1
POST http://localhost:7071/api/map-security
Content-Type: application/json

[
{
  "company_input": "Events Buyer, LLC",
  "security_input": "Events buyer Term loan"
}
]
### 2
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "48forty Intermediate Holdings, Inc.",
  "security_input": "48Forty Intermediate Holdings common equity 1506"
}

### 3
POST http://localhost:7071/api/map-security
Content-Type: application/json

[
{
  "company_input": "48forty Intermediate Holdings, Inc.",
  "security_input": "48Forty Intermediate Holdings C/S"
}
]
### 4
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Aechelon Technology Inc.",
  "security_input": "Aechelon Technology  T/L "
}

### 5
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "AFC-Dell Holding Corp.",
  "security_input": "AFC-Dell Holding DD T/L (12/23)"
}

### 6
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "AFC-Dell Holding Corp.",
  "security_input": "AFC-Dell Holding T/L"
}

### 7
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Burgess Point Purchaser Corporation",
  "security_input": "Burgess Point Purchaser Corporation (BBB)  T/L (06/22)"
}

### 8
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "BLC Holding Company, Inc.",
  "security_input": "BLC Holding Company DD T/L"
}

### 9
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Bluebird Group LLC, The",
  "security_input": "Bluebird Group T/L"
}

### 10
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Aegis Technologies Group, LLC, The",
  "security_input": "Aegis Technologies Group (BlueHalo) 4th Amend T/L"
}

### 11
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "BlueHalo Global Holdings, LLC",
  "security_input": "BlueHalo Global (Aegis) T/L 4th Amend  **DUPLICATE - PLEASE USE BL0623316**"
}

### 12
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "By Light Professional IT Services LLC",
  "security_input": "By Light Professional R/C 2"
}

### 13
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Lightspeed Buyer, Inc.",
  "security_input": "Lightspeed Buyer VT1 R/C"
}

### 14
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Dr. Squatch, LLC",
  "security_input": "Dr. Squatch T/L"
}

### 15
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "GGG Midco, LLC",
  "security_input": "GGG Midco DD T/L"
}

### 16
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Infinity Home Services Holdco, Inc",
  "security_input": "Infinity Home Services Holdco Amend. 1 DD T/L"
}

### 17
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Lash Opco, LLC",
  "security_input": "Lash Opco Restatement T/L--MC178414"
}

### 18
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "OSP EMBEDDED PURCHASER, LLC",
  "security_input": "OSP Embedded Purchaser Incremental T/L (11/24)"
}

### 19
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Anteriad, LLC",
  "security_input": "Anteriad (MeritDirect) Incremental T/L B"
}

### 20
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "MeritDirect, LLC",
  "security_input": "MeritDirect T/L A (MeritB2B/Anteriad)"
}

### 21
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "OSG Topco Holdings LLC - Class A Unit",
  "security_input": "OSG Topco Holdings LLC - Class A Unit"
}

### 22
POST http://localhost:7071/api/map-security
Content-Type: application/json


{
  "company_input": "Pragmatic Institute, LLC",
  "security_input": "Pragmatic Institute C/S (03/25)"
}

### 23
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Paving Lessor Corp.",
  "security_input": "Paving Lessor Initial T/L"
}

### 24
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Lightspeed Buyer, Inc.",
  "security_input": "Lightspeed Buyer T/L"
}

### 25
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "NFS - CFP Holdings LLC",
  "security_input": "NFS - CFP Holdings Incremental T/L"
}

### 26
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "DRS Holdings III, Inc.",
  "security_input": "DRS Holdings III Amendment No. 4 Incremental T/L"
}

### 27
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Arcline FM Holdings LLC",
  "security_input": "Arcline FM Holdings T/L (7/24) (Fairbanks Morse) - Target "
}

### 28
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Management Consulting & Research, LLC",
  "security_input": "Management Consulting & Research T/L (Systems Planning and Analysis)"
}

### 29
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "PlayPower, Inc.",
  "security_input": "PlayPower T/L (5/19)"
}

### 30
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "PlayPower, Inc.",
  "security_input": "PlayPower T/L (08/24)"
}

#
### 31
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "The Track Branson Opco, LLC",
  "security_input": "The Track Branson Opco DDTL"
}

### 32
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Sath Industries LLC",
  "security_input": "Sath Industries LLC Delayed Draw Term Loan (360DG)2209 "
}
###
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "ABC Industries LLC",
  "security_input": "ABC Industries LLC Delayed Draw Term Loan (360DG)"
}
### 33
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "48Forty Intermediate Holdings Inc",
  "security_input": "48forty Common Equity"
}

### 34

POST http://localhost:7071/api/map-security
Content-Type: application/json

[
  {
    "company_input": "LAV Gear Holdings Inc",
    "security_input": "Fourteenth Amendment Priority Term Loan"
  }
]
### 35
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Burgess Point Purchaser Corporation",
  "security_input": "Burgess Point Purchaser Corporation term loan 4th amendment"
}

### 36
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Big Top Holdings LLC",
  "security_input": "Term Loan"
}

### 37
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "BlueHalo Global Holdings LLC",
  "security_input": "Initial Term Loan"
}

### 38
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "ACP Falcon Buyer Inc",
  "security_input": "Initial Term Loan"
}

### 39
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Kinetic Purchaser LLC",
  "security_input": "Closing Date Term Loan"
}

### 40
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Radius Aerospace Inc",
  "security_input": "Radius Aerospace Inc UK Term Loan"
}

### 41
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "RRA Corporate LLC",
  "security_input": "RRA Corporate LLC Initial Term Loan"
}

### 42
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TMII Enterprises LLC",
  "security_input": "TMII Enterprises LLC DDTL 1st amendment"
}

### 43
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TMII Enterprises LLC",
  "security_input": "TMII Enterprises LLC Term Loan A"
}

### 44
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "SV-Aero Holdings LLC",
  "security_input": "SV-Aero Holdings LLC Term Loan"
}

### 45
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "DRS Holdings III Inc",
  "security_input": "DRS Holdings III Inc 3/25 Term Loan"
}

### 46
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Systems Planning and Analysis Inc",
  "security_input": "Systems Planning and Analysis Inc Delayed Draw Term Loan A"
}

### 47
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "North American Rail Solutions",
  "security_input": "North American Rail Solutions USD Term Loan"
}

### 48
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "SMX Group LLC",
  "security_input": "SMX Group LLC Term Loan (Smartronix/Trident)"
}

### 49
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "STG Distribution LLC",
  "security_input": "STG Distribution LLC First Out New Money Term Loan"
}

### 50
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Zips Car Wash LLC",
  "security_input": "Zips Car Wash LLC Roll Up Term Loan"
}

### 51
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "LAV Gear Holdings, Inc.",
  "security_input": "LAV Gear Holdings, Inc. First Lien - Term Loan - 12th Amend. - Priority FOTL"
}

### 52
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "A1 Garage Equity, LLC",
  "security_input": "A1 Garage Equity, LLC Common Equity"
}

### 53
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Archer Lewis, LLC",
  "security_input": "Archer Lewis, LLC First Lien - Revolver - Revolver"
}

### 54
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Beta Plus Technologies, Inc.",
  "security_input": "Beta Plus Technologies, Inc. Initial Term Loan"
}

### 55
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Rural Sourcing Holdings, Inc.",
  "security_input": "Rural Sourcing Holdings, Inc. Amendment No. 1 Incremental Term Loans"
}

### 56
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TCG 3.0 Jogger Acquisitionco, Inc.",
  "security_input": "TCG 3.0 Jogger Acquisitionco, Inc. First Lien - Revolver - Revolver"
}

### 57
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Carnegie Dartlet, LLC",
  "security_input": "Carnegie Dartlet, LLC First Lien - DDTL - DDTL"
}

### 58
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Medina Health, LLC",
  "security_input": "Medina Health, LLC Revolving Loan"
}

### 59
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "GAUGE ETE BLOCKER LLC",
  "security_input": "GAUGE ETE BLOCKER LLC Common Equity"
}

### 60
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "EDS TOPCO, LP",
  "security_input": "EDS TOPCO, LP Common Equity"
}

### 61
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "ENC Parent Corporation",
  "security_input": "ENC Parent Corporation Initial Term Loan (First Lien)"
}

### 62
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Best Practice Associates, LLC",
  "security_input": "Best Practice Associates, LLC First Lien - Term Loan"
}

### 63
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Infinity Home Services Holdco, Inc.",
  "security_input": "Infinity Home Services Holdco, Inc. Revolving Loan"
}

### 64
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "MidOcean JF Holdings Corp.",
  "security_input": "MidOcean JF Holdings Corp. 5th Amendment Term Loan"
}

### 65
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "4Wall Entertainment",
  "security_input": "4Wall Entertainment"
}

### 66
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Aeronix",
  "security_input": "Aeronix"
}

### 67
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Any Hour Services",
  "security_input": "Any Hour Services"
}

### 68
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Any Hour Services",
  "security_input": "Any Hour Services"
}

### 69
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Cano Health",
  "security_input": "Cano Health"
}

### 70
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Dr. Scholl's",
  "security_input": "Dr. Scholl's"
}

### 71
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Infinity Home Services",
  "security_input": "Infinity Home Services"
}

### 72
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "KNS",
  "security_input": "KNS"
}

### 73
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Recteq",
  "security_input": "Recteq"
}

### 74
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "HV Watterson Holdings, LLC",
  "security_input": "HV Watterson Holdings, LLC - Unfunded Revolver"
}

### 75
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Watchtower Buyer, LLC",
  "security_input": "Watchtower Buyer, LLC - Unfunded Revolver"
}

### 76
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Univista Insurance",
  "security_input": "Univista Insurance - Common Equity"
}

### 77
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Project Granite Buyer, Inc.",
  "security_input": "Project Granite Buyer, Inc. - Unfunded Term Loan"
}

### 78
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TransGo, LLC",
  "security_input": "Aftermarket Drivetrain Products Holdings, LLC - Common Equity"
}

### 79
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "STG Distribution, LLC",
  "security_input": "STG Distribution, LLC - Second Out Term Loans"
}

### 80
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Rural Sourcing Holdings, Inc",
  "security_input": "Rural Sourcing Holdings, Inc. - Unfunded Revolver"
}
### 81
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Schlesinger Global, Inc.",
  "security_input": "Gauge Schlesinger Coinvest, LLC - Common Equity"
}

### 82
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Pacific Purchaser, LLC",
  "security_input": "Pacific Purchaser, LLC - Unfunded Revolver"
}

### 83
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Aechelon InvestCo, LP - Common Equity",
}

### 84
### 83
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TCG 3.0 Jogger Co-Invest, LP - Common Equity"
  "security_input": "Aechelon InvestCo, LP - Common Equity"
}

### 84
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "TCG 3.0 Jogger Acquisitionco, Inc.",
  "security_input": "TCG 3.0 Jogger Co-Invest, LP - Common Equity"
}

### 85
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Knexus Holdco, LLC",
  "security_input": "Knexus Holdco, LLC - preferred Equity"
}

### 86
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Connatix Buyer, Inc.",
  "security_input": "Connatix Parent, LLC - Common Equity"
}

### 87
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Connatix Buyer, Inc.",
  "security_input": "Connatix Parent, LLC - Preferred Equity"
}

### 88
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "RFMG Parent, LP - Common Equity",
  "security_input": "RFMG Parent, LP - Common Equity"
}

### 89
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "project Granite Holdings",
  "security_input": "Project Granite Holdings, LLC - Common Equity"
}

### 90
### 90
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Tyto Athene, LLC",
  "security_input": "NXOF Holdings, Inc. - Common Equity
}

### 91
### 91
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Tyto Athene, LLC"
  "security_input": "NXOF Holdings, Inc. - Preferred Equity"
}

### 92
### 92
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "The Vertex Companies, LLC"
  "security_input": "TWD Parent Holdings, LLC - Common Equity"
}

### 93
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "The Vertex Companies, LLC",
  "security_input": "TWD Parent Holdings, LLC - Preferred Equity"
}

### 94
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "Watchtower Holdings, LLC - Common Equity",
  "security_input": "Watchtower Holdings, LLC - Common Equity"
}

### 95
POST http://localhost:7071/api/map-security
Content-Type: application/json

{
  "company_input": "HV Watterson Holdings, LLC",
  "security_input": "HV Watterson Holdings, LLC - Common Equity"
}